### ISSUE TITLE
请问是否允许二次封装

### ISSUE THREAD

**Issue by rmlzy** [Moonvy/Figma-Net-OK#1]
您好，您的代码对我来说十分有用，为了方便使用，我将您的代码封装成了 node 的工具，参见: https://github.com/rmlzy/fast-figma

您的代码未声明 License，不知道您是否允许二次封装，如果不允许的话可以留言给我，我将第一时间删除。

感谢您的贡献。

**Comment by yArna** [comment]
没有问题

**Comment by rmlzy** [comment]
感谢
