### ISSUE TITLE
Got an undefined error

### ISSUE THREAD

**Issue by beginor** [Moonvy/Figma-Net-OK#2]
I have tried you Figma-Net-OK, but got an undefined error:

<img width="396" alt="Screen Shot 2021-10-16 at 10 25 28" src="https://user-images.githubusercontent.com/159065/137570108-bf2caa6b-d555-4357-87ea-2bc9de32013a.png">

**Comment by yArna** [comment]
This should be fixed in the new version [v2.1.0](https://github.com/Moonvy/Figma-Net-OK/releases/tag/v2.1.0)
